# Generated by Django 4.0.4 on 2022-05-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='餐廳名字')),
                ('Style', models.CharField(max_length=50, verbose_name='餐廳類型')),
                ('Price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='價位')),
                ('Img', models.ImageField(blank=True, upload_to='Restaurant_Image/', verbose_name='餐廳圖片')),
                ('Distance', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='與學校距離')),
                ('Address', models.CharField(max_length=50, verbose_name='餐廳地址')),
                ('Rating', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='價位')),
            ],
        ),
    ]
