# Generated by Django 4.0.4 on 2022-06-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_alter_restaurant_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Rating',
        ),
    ]
